[window]
opacity = 0.75

[general]
import = [
    "~/.config/alacritty/themes/siva.toml"
]

[selection]
save_to_clipboard = true

[font]
normal = { family = "JetBrains Mono", style = "Regular"}

bold = { style = "Regular" }

italic = { style = "Italic" }

bold_italic = { style="Italic" }
